In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
df_enem = pd.read_csv('MICRODADOS_ENEM_2019_SAMPLE_43278.csv')
# df = pd.read_csv('MICRODADOS_ENEM_2019_SAMPLE_43278.csv',usecols=) #seleciona quais colunas voce pretende utilizar
df_enem

,NU_INSCRICAO,NU_ANO,CO_MUNICIPIO_RESIDENCIA,NO_MUNICIPIO_RESIDENCIA,CO_UF_RESIDENCIA,SG_UF_RESIDENCIA,NU_IDADE,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,...,Q016,Q017,Q018,Q019,Q020,Q021,Q022,Q023,Q024,Q025
0,190001004661,2019,1506138,Redenção,15,PA,17,M,1,3,...,A,A,A,A,B,A,C,A,B,B
1,190001004674,2019,1504208,Marabá,15,PA,23,M,1,3,...,A,A,A,B,A,A,B,A,A,B
2,190001004722,2019,1501402,Belém,15,PA,35,F,2,1,...,A,A,A,B,A,B,B,A,A,B
3,190001004735,2019,1507300,São Félix do Xingu,15,PA,23,F,1,3,...,A,A,A,B,A,A,B,A,A,B
4,190001004776,2019,1500800,Ananindeua,15,PA,16,F,1,3,...,A,A,A,B,A,A,D,A,A,B
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127375,190006120035,2019,3142700,Montalvânia,31,MG,17,F,1,1,...,A,A,A,B,A,A,D,A,B,B
127376,190006120036,2019,2902807,Barra da Estiva,29,BA,18,M,1,2,...,A,A,A,B,A,A,D,A,B,B
127377,190006120037,2019,2927408,Salvador,29,BA,22,F,1,3,...,A,A,A,A,A,A,B,A,A,B
127378,190006120060,2019,2930709,Simões Filho,29,BA,26,F,2,2,...,A,A,A,B,A,A,C,A,A,A
127379,190006120170,2019,3106200,Belo Horizonte,31,MG,19,M,1,2,...,A,A,A,B,A,A,B,B,A,B

- filtrar colunas : pegar só quem fez, depois pegar notas e fazer média
- definir perfil dos aprovados ~~medicina~~ (considerando 800 pontos como media)
- considerar aqui perfil de quem tem media superior a 800
- porcentagem, sexo, raca, etnia, estado ....

In [10]:
df_enem.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 127380 entries, 0 to 127379
Columns: 136 entries, NU_INSCRICAO to Q025
dtypes: float64(24), int64(71), object(41)
memory usage: 132.2+ MB

In [13]:
df_enem['NOTA_FINAL'] = df_enem[['NU_NOTA_CN','NU_NOTA_CH','NU_NOTA_LC','NU_NOTA_MT']].mean(axis=1)
df_enem

,NU_INSCRICAO,NU_ANO,CO_MUNICIPIO_RESIDENCIA,NO_MUNICIPIO_RESIDENCIA,CO_UF_RESIDENCIA,SG_UF_RESIDENCIA,NU_IDADE,TP_SEXO,TP_ESTADO_CIVIL,TP_COR_RACA,...,Q017,Q018,Q019,Q020,Q021,Q022,Q023,Q024,Q025,NOTA_FINAL
0,190001004661,2019,1506138,Redenção,15,PA,17,M,1,3,...,A,A,A,B,A,C,A,B,B,467.225
1,190001004674,2019,1504208,Marabá,15,PA,23,M,1,3,...,A,A,B,A,A,B,A,A,B,392.300
2,190001004722,2019,1501402,Belém,15,PA,35,F,2,1,...,A,A,B,A,B,B,A,A,B,447.625
3,190001004735,2019,1507300,São Félix do Xingu,15,PA,23,F,1,3,...,A,A,B,A,A,B,A,A,B,513.925
4,190001004776,2019,1500800,Ananindeua,15,PA,16,F,1,3,...,A,A,B,A,A,D,A,A,B,505.875
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127375,190006120035,2019,3142700,Montalvânia,31,MG,17,F,1,1,...,A,A,B,A,A,D,A,B,B,531.850
127376,190006120036,2019,2902807,Barra da Estiva,29,BA,18,M,1,2,...,A,A,B,A,A,D,A,B,B,424.625
127377,190006120037,2019,2927408,Salvador,29,BA,22,F,1,3,...,A,A,A,A,A,B,A,A,B,506.950
127378,190006120060,2019,2930709,Simões Filho,29,BA,26,F,2,2,...,A,A,B,A,A,C,A,A,A,488.475
127379,190006120170,2019,3106200,Belo Horizonte,31,MG,19,M,1,2,...,A,A,B,A,A,B,B,A,B,451.950